name: 'LeanCloud Self Wake'

 # 触发条件
on:
  push:
  watch:
    types: [started]
  schedule:
    - cron: '*/10 23-23 * * ?'    
    - cron: '*/10 0-15 * * ?'     

jobs:
  curl-my-site:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'
         env:
           MY_SITE: ${{ secrets.SITE }}
         # 向站点发送 GET 请求
         run: |                                   
           curl $MY_SITE
